### PR TITLE
Remove limit

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
This PR removes the 50-item limit.

I'll remove the [WIP] once `vagrant up` finishes and I can test it

### CODE REVIEW

**Comment by waxlamp** [comment]
Oops. My trigger finger was itchy, sorry!

Let me know if `vagrant up` has problems and in that case we can revert the merge and fix any lingering problems.

**Comment by alex-r-bigelow** [comment]
I'm actually having a `vagrant up` problem, but there's a good chance it's my local ansible/vagrant installation (first time setting up on this machine):

```
fatal: [demohost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"apiRoot": null, "assetstore": null, "blacklist": null, "delete": null, "dryrun": null, "get": null, "host": null, "password": null, "plugins": null, "port": "8080", "post": null, "put": null, "scheme": null, "state": "present", "token": null, "user": "{'firstName': 'Admin', 'admin': True, 'lastName': 'User', 'login': 'admin', 'password': 'adminadmin', 'email': 'admin@example.com'}", "username": null}, "module_name": "girder"}, "msg": "<type 'exceptions.TypeError'>: user() takes at least 3 arguments (2 given)

Traceback (most recent call last):
  File \"/tmp/ansible_52ie_j/ansible_module_girder.py\", line 836, in main
    gcm(module)
  File \"/tmp/ansible_52ie_j/ansible_module_girder.py\", line 520, in __call__
    self.__process(method)
  File \"/tmp/ansible_52ie_j/ansible_module_girder.py\", line 548, in __process
    ret = getattr(self, method)(*args, **kwargs)
TypeError: user() takes at least 3 arguments (2 given)
"}
```

Any clues?

**Comment by waxlamp** [comment]
What version of Ansible and Vagrant do you have installed?

**Comment by alex-r-bigelow** [comment]
ansible: 2.1.0.0
vagrant: 1.8.1

**Comment by waxlamp** [comment]
Strange. I'll give it a go on my machine, since I haven't run into trouble
with Vagrant/Ansible before.

**Comment by waxlamp** [comment]
Looks like the build went just fine.

**Comment by alex-r-bigelow** [comment]
Could you verify that a dataset with >50 items will load?

**Comment by waxlamp** [comment]
Not entirely sure how to tell, but I did load up the nanoparticles data and it's showing me that there are 3287 items in the "polymer" set. Does that mean it's working?

**Comment by alex-r-bigelow** [comment]
I think so—connecting it to UpSet would be one way to be absolutely sure (I think you have to explicitly tell it that the _id field is a string to force the conversion)

**Comment by curtislisle** [comment]
It sounds like it is working.  I use “NanoparticleID” as the index for UpSet, since this is a unique ID number.

**Comment by curtislisle** [comment]
If I checkout the correct candela commit, restart girder, and then do “npm install” in the /opt/girder directory, this will update the candela version, right?  I did it before, just am not sure I remember the steps correctly.

**Comment by waxlamp** [comment]
@curtislisle why don't we do a quick hangout if you have a few minutes. I'm not sure `npm install` is the right way to update things.

**Comment by curtislisle** [comment]
@ronichoudhury,
thanks.  I’ll try to call about 1:30pm for just a few minutes.

**Comment by waxlamp** [comment]
Curt and I just confirmed (via hangout) that this is working correctly. We have a remaining issue (not related to this PR) that we can discuss in our upcoming call.

**Comment by waxlamp** [comment]
@alex-r-bigelow if you're finished with the branch could you go ahead and delete it? Thanks.

**Pull request merged**
